### ISSUE TITLE
Converting Raw certificate output to PEM?

### ISSUE THREAD

**Issue by 4oo4** [darrenjrobinson/YubiKey#1]
I was attempting to convert the output of `-Raw $true` into a PEM certificate by adding the being/end certificate headers and adding line breaks, but did not have much luck. Is there a better way that I can get the raw output into a usable certificate format?

**Comment by darrenjrobinson** [comment]
It would likely be easier to convert to PEM from x509Cert than Base64String (Raw). 
I vaguely recall such a method. 
I'll investigate.

**Comment by darrenjrobinson** [comment]
Added option to export cert as PEM using built-in function. 
https://github.com/darrenjrobinson/YubiKey/blob/main/YubiKey.ps1
